import { Button } from '@heroui/react/button';
import { Card } from '@heroui/react/card';
import { Chip } from '@heroui/react/chip';
import { Disclosure } from '@heroui/react/disclosure';
import { Table } from '@heroui/react/table';
import { DIET_FOODS } from '../engine/foods';
import type { InferenceResult, DietType, BMICategory } from '../engine/types';

interface Props {
  result: InferenceResult;
  onReset: () => void;
}

const BMI_COLOR: Record<BMICategory, 'default' | 'success' | 'warning' | 'danger'> = {
  Underweight: 'default',
  Normal:      'success',
  Overweight:  'warning',
  Obese:       'danger',
};

const DIET_COLOR: Partial<Record<DietType, 'default' | 'success' | 'warning' | 'danger' | 'accent'>> = {
  DASH:     'default',
  'Low-GI': 'accent',
};

function formatFactValue(val: unknown): string {
  if (Array.isArray(val))
    return `[${val.slice(0, 2).join(', ')}${val.length > 2 ? `, …+${val.length - 2}` : ''}]`;
  return String(val);
}

export function Step3({ result, onReset }: Props) {
  const { facts, trace } = result;
  const dietType = facts.diet_type as DietType | undefined;
  const avoidFoods = dietType ? (DIET_FOODS[dietType]?.avoid ?? []) : [];

  const carbPct = facts.target_calories
    ? Math.round(((facts.carb_g ?? 0) * 4 / facts.target_calories) * 100) : 0;
  const protPct = facts.target_calories
    ? Math.round(((facts.protein_g ?? 0) * 4 / facts.target_calories) * 100) : 0;
  const fatPct = facts.target_calories
    ? Math.round(((facts.fat_g ?? 0) * 9 / facts.target_calories) * 100) : 0;

  return (
    <div className="w-full max-w-2xl mx-auto space-y-5">
      {/* Page header */}
      <div className="text-center">
        <h2 className="text-2xl font-bold text-gray-900">Your Personalized Diet Plan</h2>
        <p className="text-gray-500 text-sm mt-1">
          Generated by NutriChain Forward Chaining Engine — {trace.length} inference steps
        </p>
      </div>

      {/* Biometric stat cards */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
        <Card className="text-center p-4">
          <span className="text-xs font-semibold text-gray-500 uppercase tracking-wide">BMI</span>
          <span className="text-2xl font-bold text-gray-900 mt-1 block">{facts.bmi}</span>
          {facts.bmi_category && (
            <Chip size="sm" color={BMI_COLOR[facts.bmi_category]} className="mt-2">
              {facts.bmi_category}
            </Chip>
          )}
        </Card>

        <Card className="text-center p-4">
          <span className="text-xs font-semibold text-gray-500 uppercase tracking-wide">BMR</span>
          <span className="text-2xl font-bold text-gray-900 mt-1 block">{facts.bmr}</span>
          <span className="text-xs text-gray-400 mt-1 block">kcal/day (rest)</span>
        </Card>

        <Card className="text-center p-4">
          <span className="text-xs font-semibold text-gray-500 uppercase tracking-wide">TDEE</span>
          <span className="text-2xl font-bold text-gray-900 mt-1 block">{facts.tdee}</span>
          <span className="text-xs text-gray-400 mt-1 block">kcal/day (active)</span>
        </Card>

        <Card className="text-center p-4 border-green-300 bg-green-50">
          <span className="text-xs font-semibold text-green-700 uppercase tracking-wide">Target ★</span>
          <span className="text-2xl font-bold text-green-800 mt-1 block">{facts.target_calories}</span>
          <span className="text-xs text-green-600 mt-1 block">kcal/day</span>
        </Card>
      </div>

      {/* Diet type + macros card */}
      <Card>
        <Card.Content className="space-y-4">
          <div className="flex items-center justify-between flex-wrap gap-3">
            <div className="flex items-center gap-3">
              <h3 className="text-base font-semibold text-gray-700">Diet Type</h3>
              {dietType && (
                <Chip color={DIET_COLOR[dietType] ?? 'success'}>
                  {dietType} Diet
                </Chip>
              )}
            </div>
            <div className="flex flex-wrap gap-4 text-sm text-gray-600">
              {facts.sodium_limit_mg && (
                <span><span className="font-medium">Sodium:</span> {facts.sodium_limit_mg} mg/day</span>
              )}
              {facts.carb_limit_pct && (
                <span><span className="font-medium">Carb limit:</span> ≤ {facts.carb_limit_pct}%</span>
              )}
            </div>
          </div>

          {facts.carb_g && (
            <div className="space-y-2">
              <h3 className="text-sm font-semibold text-gray-600">Daily Macronutrients</h3>
              <div className="h-4 rounded-full overflow-hidden flex bg-gray-100">
                <div className="bg-blue-400 h-full transition-all" style={{ width: `${carbPct}%` }} title={`Carbs ${carbPct}%`} />
                <div className="bg-green-500 h-full transition-all" style={{ width: `${protPct}%` }} title={`Protein ${protPct}%`} />
                <div className="bg-amber-400 h-full transition-all" style={{ width: `${fatPct}%` }} title={`Fat ${fatPct}%`} />
              </div>
              <div className="flex flex-wrap gap-4 text-sm text-gray-600">
                <span>
                  <span className="inline-block w-3 h-3 rounded-full bg-blue-400 mr-1 align-middle" />
                  Carbs {facts.carb_g}g ({carbPct}%)
                </span>
                <span>
                  <span className="inline-block w-3 h-3 rounded-full bg-green-500 mr-1 align-middle" />
                  Protein {facts.protein_g}g ({protPct}%)
                </span>
                <span>
                  <span className="inline-block w-3 h-3 rounded-full bg-amber-400 mr-1 align-middle" />
                  Fat {facts.fat_g}g ({fatPct}%)
                </span>
              </div>
            </div>
          )}
        </Card.Content>
      </Card>

      {/* Food lists */}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <Card>
          <Card.Content>
            <h3 className="text-sm font-semibold text-green-700 mb-3">Recommended Foods</h3>
            <ul className="space-y-1.5">
              {(facts.recommended_foods ?? []).map((f, i) => (
                <li key={i} className="flex items-start gap-2 text-sm text-gray-700">
                  <span className="text-green-600 font-bold shrink-0">✓</span>{f}
                </li>
              ))}
            </ul>
          </Card.Content>
        </Card>

        <Card>
          <Card.Content>
            <h3 className="text-sm font-semibold text-red-600 mb-3">Foods to Avoid</h3>
            <ul className="space-y-1.5">
              {avoidFoods.map((f, i) => (
                <li key={i} className="flex items-start gap-2 text-sm text-gray-700">
                  <span className="text-red-500 font-bold shrink-0">✕</span>{f}
                </li>
              ))}
            </ul>
          </Card.Content>
        </Card>
      </div>

      {/* Allergen blacklist */}
      {(facts.blacklisted_foods ?? []).length > 0 && (
        <Card>
          <Card.Content>
            <h3 className="text-sm font-semibold text-amber-700 mb-1">Allergen Blacklist</h3>
            <p className="text-xs text-gray-500 mb-3">
              Eliminated from your plan based on declared allergies.
            </p>
            <ul className="grid grid-cols-2 gap-1.5">
              {(facts.blacklisted_foods ?? []).map((f, i) => (
                <li key={i} className="flex items-center gap-2 text-sm text-gray-700">
                  <span className="text-amber-600 shrink-0">⊘</span>{f}
                </li>
              ))}
            </ul>
          </Card.Content>
        </Card>
      )}

      {/* Inference trace (Disclosure + Table) */}
      <Card>
        <Card.Content>
          <Disclosure>
            <Disclosure.Heading>
              <Disclosure.Trigger className="flex items-center justify-between w-full py-1 text-left font-semibold text-gray-700">
                <span>Inference Trace</span>
                <div className="flex items-center gap-2">
                  <span className="text-xs bg-gray-100 text-gray-500 px-2 py-0.5 rounded-full">
                    {trace.length} iterations
                  </span>
                  <Disclosure.Indicator />
                </div>
              </Disclosure.Trigger>
            </Disclosure.Heading>
            <Disclosure.Content className="mt-3">
              <Table className="table__scroll-container">
                <Table.Content aria-label="Inference trace" className="min-w-[720px] w-full text-sm">
                  <Table.Header>
                    <Table.Column className="text-left py-2 px-3 text-xs font-semibold text-gray-500 uppercase">#</Table.Column>
                    <Table.Column className="text-left py-2 px-3 text-xs font-semibold text-gray-500 uppercase">Rule Fired</Table.Column>
                    <Table.Column className="text-left py-2 px-3 text-xs font-semibold text-gray-500 uppercase">Description</Table.Column>
                    <Table.Column className="text-left py-2 px-3 text-xs font-semibold text-gray-500 uppercase">New Facts</Table.Column>
                    <Table.Column className="text-left py-2 px-3 text-xs font-semibold text-gray-500 uppercase">CS</Table.Column>
                  </Table.Header>
                  <Table.Body>
                    {trace.map((entry) => (
                      <Table.Row key={entry.iteration} id={String(entry.iteration)} className="border-t border-gray-100 hover:bg-gray-50">
                        <Table.Cell className="py-2 px-3 text-gray-500 tabular-nums">{entry.iteration}</Table.Cell>
                        <Table.Cell className="py-2 px-3">
                          <code className="text-xs font-mono text-indigo-600">{entry.rule_fired}</code>
                        </Table.Cell>
                        <Table.Cell className="py-2 px-3 text-gray-600 text-xs max-w-xs">{entry.rule_description}</Table.Cell>
                        <Table.Cell className="py-2 px-3">
                          {Object.entries(entry.new_facts).map(([k, v]) => (
                            <div key={k} className="text-xs font-mono">
                              <span className="text-green-700">{k}</span>
                              {' = '}
                              <span className="text-gray-500">{formatFactValue(v)}</span>
                            </div>
                          ))}
                        </Table.Cell>
                        <Table.Cell className="py-2 px-3 text-center text-gray-500">{entry.conflict_set.length}</Table.Cell>
                      </Table.Row>
                    ))}
                  </Table.Body>
                </Table.Content>
              </Table>
            </Disclosure.Content>
          </Disclosure>
        </Card.Content>
      </Card>

      <div className="flex justify-start">
        <Button variant="ghost" size="lg" onPress={onReset}>Start Over</Button>
      </div>
    </div>
  );
}
